(let ((_ (load "alist.scm"))
      (sexp '((:a (:b 1) (c 2)))))
  (format #t "before: ~A~%" (assoc-in '(:a :b) sexp))
  (alist-update-in! sexp '(:a :b)
                    (lambda (old)
                      (list 99)))
  (format #t "after: ~A~%" (assoc-in '(:a :b) sexp))
  sexp)

(let ((_ (load "alist.scm"))
      (sexp '((:a (:b 1) (:c 2)))))
  (format #t "before: ~A~%" (assoc-in '(:a :b) sexp))
  (alist-update-in! sexp '(:a :x)
                    (lambda (old)
                      (format #t "~A: ~A~%" (red "user fn, old val:") old)
                      (list 99)))
  (format #t "after: ~A~%" (assoc-in '(:a :b) sexp))
  sexp)

(let ((_ (load "alist.scm"))
      (sexp '((:a (:b (:z 1)) (:c 2)))))
  (format #t "before: ~A~%" (assoc-in '(:a :b :x) sexp))
  (alist-update-in! sexp '(:a :b :x)
                    (lambda (old)
                      (format #t "~A: ~A~%" (red "user fn, old val:") old)
                      (list 99)))
  (format #t "after: ~A~%" (assoc-in '(:a :b :x) sexp))
  sexp)


