(varlet (rootlet)
        'regcomp (*libc* 'regcomp)
        'regex.make (*libc* 'regex.make)
        'regexec (*libc* 'regexec)
        'regfree (*libc* 'regfree)
        'REG_EXTENDED (*libc* 'REG_EXTENDED))
